Repository DynxstyGIT/DIH4JDA, pull requests merged in 2022-11, with the labels that each got.

#60 Refactored & Abstracted `DIH4JDAEvent`s
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/events/AutoCompleteExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/CommandExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ComponentExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEventListener.java
  src/main/java/xyz/dynxsty/dih4jda/events/GenericDIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InsufficientPermissionsEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidRoleEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidUserEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ModalExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ThrowableDIH4JDAEvent.java
Labels: enhancement, breaking

#62 Integrated JDA's command-entities into `SlashCommand` & `SlashCommand.Subcommand` & made SmartQueue non-blocking
  build.gradle.kts
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/events/GenericDIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ThrowableDIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/ExecutableCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/SlashCommand.java
  src/main/java/xyz/dynxsty/dih4jda/util/AutoCompleteUtils.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
Labels: enhancement, breaking, new feature

#64 Refactored Internal Command Structure
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/events/AutoCompleteExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/CommandExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEventListener.java
  src/main/java/xyz/dynxsty/dih4jda/events/InsufficientPermissionsEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidRoleEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidUserEvent.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/AutoCompletable.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/ContextCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/RestrictedCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/ApplicationCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/BaseApplicationCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/ContextCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/RegistrationType.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/EntitySelectMenuHandler.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/ModalHandler.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/StringSelectMenuHandler.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
  src/test/java/com/dynxsty/tests/ComponentIdTest.java
Labels: enhancement, breaking

#65 Command Cooldowns
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/events/CommandCooldownEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEventListener.java
  src/main/java/xyz/dynxsty/dih4jda/events/GenericDIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/RestrictedCommand.java
Labels: enhancement, new feature

#68 Introduce IdMappings
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/RestrictedCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/ContextCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/IdMapping.java
Labels: enhancement

#70 Javadocs via GitHub Pages
  .github/workflows/javadocs.yml
Labels: documentation, enhancement

#73 Add missing `package-info.java` Files
  src/main/java/xyz/dynxsty/dih4jda/config/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/events/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/package-info.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/package-info.java
Labels: documentation

#75 Config Constructor
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/InvalidConfigurationException.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/InvalidPackageException.java
Labels: enhancement

#76 Added support for Localized Commands
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
Labels: enhancement, new feature

#78 Added more Examples
  src/examples/java/xyz/dynxsty/examples/commands/ping/PingCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/ping/PingRoleCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/ping/PingUserSubCommand.java
Labels: documentation, enhancement

#79 Exception to Throwable
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
Labels: enhancement

#80 Fix classwalker
  src/main/java/xyz/dynxsty/dih4jda/util/ClassWalker.java
Labels: bugfix

#82 Simplified `CommandUtils#equals`
  build.gradle.kts
  src/examples/java/xyz/dynxsty/examples/commands/DeleteContextCommand.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
Labels: enhancement, new feature

#83 added missing annotations
  src/examples/java/xyz/dynxsty/examples/commands/AutoCompletedCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/DeleteContextCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/LocalizedCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/PollCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/SayCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/ping/PingRoleCommand.java
  src/examples/java/xyz/dynxsty/examples/commands/ping/PingUserSubCommand.java
  src/examples/java/xyz/dynxsty/examples/listeners/DIH4JDAListener.java
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDALogger.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/events/AutoCompleteExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/CommandCooldownEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/CommandExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ComponentExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAEventListener.java
  src/main/java/xyz/dynxsty/dih4jda/events/DIH4JDAThrowableEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InsufficientPermissionsEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidGuildEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidRoleEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/InvalidUserEvent.java
  src/main/java/xyz/dynxsty/dih4jda/events/ModalExceptionEvent.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/CommandNotRegisteredException.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/DIH4JDAException.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/DIH4JDAReflectionException.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/InvalidConfigurationException.java
  src/main/java/xyz/dynxsty/dih4jda/exceptions/InvalidPackageException.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/ExecutableCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/RestrictedCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/ApplicationCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/BaseApplicationCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/components/IdMapping.java
  src/main/java/xyz/dynxsty/dih4jda/util/AutoCompleteUtils.java
  src/main/java/xyz/dynxsty/dih4jda/util/Checks.java
  src/main/java/xyz/dynxsty/dih4jda/util/ClassUtils.java
  src/main/java/xyz/dynxsty/dih4jda/util/ClassWalker.java
  src/main/java/xyz/dynxsty/dih4jda/util/ClasspathHelper.java
  src/main/java/xyz/dynxsty/dih4jda/util/ComponentIdBuilder.java
  src/main/java/xyz/dynxsty/dih4jda/util/IoUtils.java
  src/main/java/xyz/dynxsty/dih4jda/util/Pair.java
Labels: documentation, enhancement

#85 Added missing @since javadoc tag
  src/main/java/xyz/dynxsty/dih4jda/util/ArrayUtil.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
  src/main/java/xyz/dynxsty/dih4jda/util/IoUtils.java
Labels: documentation

#89 Optimized internal checks
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/ApplicationCommand.java
  src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
  src/main/java/xyz/dynxsty/dih4jda/util/Checks.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
Labels: enhancement

#91 Fix useless queue of subcommands
  src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
  src/main/java/xyz/dynxsty/dih4jda/util/ArrayUtil.java
  src/main/java/xyz/dynxsty/dih4jda/util/CommandUtils.java
Labels: bugfix
