Repository DynxstyGIT/DIH4JDA, pull requests merged in 2022-05, with the labels that each got.

#27 Made it possible to disable the deletion of Unknown Commands with SmartQueue
  src/main/java/com/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/com/dynxsty/dih4jda/DIH4JDABuilder.java
  src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/com/dynxsty/dih4jda/SmartQueue.java
Labels: enhancement

#28 Release v1.5.1 – Fixed Global Command Queuing & Improved Component Handling
  .github/workflows/codeql-analysis.yml
  src/main/java/com/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/com/dynxsty/dih4jda/DIH4JDABuilder.java
  src/main/java/com/dynxsty/dih4jda/DIH4JDALogger.java
  src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/com/dynxsty/dih4jda/SmartQueue.java
  src/main/java/com/dynxsty/dih4jda/config/DIH4JDAConfig.java
  src/main/java/com/dynxsty/dih4jda/events/DIH4JDAListenerAdapter.java
  src/main/java/com/dynxsty/dih4jda/interactions/ComponentIdBuilder.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/AutoCompleteHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/ComponentHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/ExecutableCommand.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/model/UnqueuedCommandData.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/model/UnqueuedSlashCommandData.java
  src/main/java/com/dynxsty/dih4jda/interactions/components/button/ButtonHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/components/select_menu/SelectMenuHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/modal/ModalHandler.java
  src/main/java/com/dynxsty/dih4jda/util/Checks.java
  src/main/java/com/dynxsty/dih4jda/util/ClassUtils.java
  src/main/java/com/dynxsty/dih4jda/util/CommandUtils.java
  src/main/java/com/dynxsty/dih4jda/util/Pair.java
  src/test/java/com/dynxsty/tests/ComponentIdTest.java
Labels: enhancement, release

#30 Release v1.5.3 – Added support for Abstract Classes & fixed some more bugs regarding SmartQueue
  build.gradle
  src/main/java/com/dynxsty/dih4jda/DIH4JDA.java
  src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/com/dynxsty/dih4jda/SmartQueue.java
  src/main/java/com/dynxsty/dih4jda/util/ClassUtils.java
  src/main/java/com/dynxsty/dih4jda/util/CommandUtils.java
Labels: release, bugfix

#32 Release v1.5.4 – `jda5.0.0-alpha.12`
  build.gradle
  src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/ComponentIdBuilder.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/CommandRequirements.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/ComponentHandler.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/ContextCommand.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/ExecutableCommand.java
  src/main/java/com/dynxsty/dih4jda/interactions/commands/SlashCommand.java
  src/main/java/com/dynxsty/dih4jda/util/Pair.java
Labels: release
